import { writeFileSync } from "fs";

function makeVehicle(marca, modelo, versao, ano, opts) {
  const {
    msrp = null,
    dataSource,
    combustivel,
    transmissao,
    tracao,
    cilindros = 4,
    configCilindros = "em linha",
    cilindrada,
    potencia,
    potenciaRpm,
    torque,
    torqueRpm,
    alimentacao = "injecao multiponto",
    marchas,
    potEletrica = null,
    torqEletrico = null,
    bateria = null,
    acel = null,
    velMax = null,
    consUrbGas = null,
    consRodGas = null,
    consUrbEta = null,
    consRodEta = null,
    autonomiaElet = null,
    co2 = null,
    comprimento,
    largura,
    altura,
    entre_eixos,
    peso,
    portaMalas,
    tanque,
    cargaUtil = null,
    aro,
    pneu,
    materialRoda = "liga-leve",
    freioDiant,
    freioTras,
    abs = true,
    ebd = true,
    ba = true,
    airbags,
    posAirbags,
    estabilidade = false,
    tracao_ctrl = false,
    rampAssist = false,
    alertColisao = false,
    aeb = false,
    alertFaixa = false,
    assistFaixa = false,
    pontoCego = false,
    cameraRe = false,
    visao360 = false,
    sensorTras = false,
    sensorDiant = false,
    ncapLatin = null,
    ncapLatinAno = null,
    ncapEuro = null,
    ncapEuroAno = null,
    cintoPre = true,
    cintoLim = false,
    isofix = false,
    tela = null,
    carplayFio = false,
    carplaySem = false,
    androidFio = false,
    androidSem = false,
    bluetooth = false,
    usbs = 0,
    tipoUsb = null,
    wireless = false,
    gps = false,
    altoFalantes = 4,
    somPremium = null,
    wifi = false,
    painelDig = false,
    painelDigPol = null,
    hud = false,
    arCond,
    direcao,
    cruiseAdapt = false,
    cruiseConv = false,
    keyless = false,
    pushStart = false,
    bancoMotElet = false,
    bancoMotPos = null,
    bancoPasElet = false,
    memBanco = false,
    bancoAqDiant = false,
    bancoAqTras = false,
    bancoVent = false,
    tetoSolar = false,
    tetoPano = false,
    desembPara = false,
    retrovElet = true,
    retrovRebat = false,
    volanteAjuste = true,
    revestimento = "tecido",
    portas = 4,
    passageiros = 5,
    fileiras = "2 fileiras",
  } = opts;

  return {
    identificacao: {
      id: `honda-${modelo.toLowerCase().replace(/[^a-z0-9]/g,"-").replace(/-+/g,"-")}-${versao.toLowerCase().replace(/[^a-z0-9]/g,"-").replace(/-+/g,"-")}-${ano}`,
      marca,
      modelo,
      versao,
      anoModelo: ano,
      msrpBrl: msrp,
      dataSource,
    },
    especificacoes: {
      motorTransmissao: {
        tipoCombustivel: combustivel,
        tipoTransmissao: transmissao,
        tipoTracao: tracao,
        numeroCilindros: cilindros,
        configuracaoCilindros: configCilindros,
        cilindradaCc: cilindrada,
        potenciaCv: potencia,
        potenciaRpm,
        torqueKgfm: torque,
        torqueRpm,
        alimentacao,
        numeroDeMarchas: marchas,
        potenciaEletricaCv: potEletrica,
        torqueEletricoKgfm: torqEletrico,
        capacidadeBateriaKwh: bateria,
      },
      desempenho: {
        aceleracao0a100Segundos: acel,
        velocidadeMaximaKmh: velMax,
        consumoUrbanoGasolinaKmL: consUrbGas,
        consumoRodoviarioGasolinaKmL: consRodGas,
        consumoUrbanoEtanolKmL: consUrbEta,
        consumoRodoviarioEtanolKmL: consRodEta,
        autonomiaEletricaKm: autonomiaElet,
        emissaoCo2GKm: co2,
      },
      dimensoesPeso: {
        comprimentoMm: comprimento,
        larguraMm: largura,
        alturaMm: altura,
        distanciaEntreEixosMm: entre_eixos,
        pesoKg: peso,
        portaMalasLitros: portaMalas,
        tanqueLitros: tanque,
        cargaUtilKg: cargaUtil,
      },
      rodasPneusFreios: {
        aroPolegadas: aro,
        especificacaoPneu: pneu,
        materialRoda,
        tipoFreiosDianteiros: freioDiant,
        tipoFreiosTraseiros: freioTras,
        abs,
        ebd,
        ba,
      },
      segurancaAtiva: {
        airbags,
        posicionamentoAirbags: posAirbags,
        controleEstabilidade: estabilidade,
        controleTracao: tracao_ctrl,
        assistentePartidaRampa: rampAssist,
        alertaColisaoFrontal: alertColisao,
        frenagemAutonomaEmergencia: aeb,
        alertaSaidaFaixa: alertFaixa,
        assistentePermanenciaFaixa: assistFaixa,
        monitorPontoCego: pontoCego,
        cameraRe,
        visao360,
        sensorEstacionamentoTraseiro: sensorTras,
        sensorEstacionamentoDianteiro: sensorDiant,
      },
      segurancaPassiva: {
        notaNcapLatinEstrelas: ncapLatin,
        anoAvaliacaoNcapLatin: ncapLatinAno,
        notaNcapEuroEstrelas: ncapEuro,
        anoAvaliacaoNcapEuro: ncapEuroAno,
        cintoPreTensionadorMotorista: cintoPre,
        cintoLimitadorForca: cintoLim,
        isofix,
      },
      tecnologiaConectividade: {
        telaCentralPolegadas: tela,
        appleCarPlayComFio: carplayFio,
        appleCarPlaySemFio: carplaySem,
        androidAutoComFio: androidFio,
        androidAutoSemFio: androidSem,
        bluetooth,
        portasUsb: usbs,
        tipoPortaUsb: tipoUsb,
        carregamentoWireless: wireless,
        gpsIntegrado: gps,
        altofaLantes: altoFalantes,
        marcaSomPremium: somPremium,
        wifiHotspot: wifi,
        painelDigital: painelDig,
        painelDigitalPolegadas: painelDigPol,
        headUpDisplay: hud,
      },
      confortoConveniencias: {
        tipoArCondicionado: arCond,
        tipoDirecao: direcao,
        cruiseControlAdaptativo: cruiseAdapt,
        cruiseControlConvencional: cruiseConv,
        keylessEntry: keyless,
        partidaBotao: pushStart,
        bancoMotoristaAjusteEletrico: bancoMotElet,
        bancoMotoristaPosicoesEletricas: bancoMotPos,
        bancoPassageiroAjusteEletrico: bancoPasElet,
        memoriaPositionBancoMotorista: memBanco,
        bancoAquecidoDianteiro: bancoAqDiant,
        bancoAquecidoTraseiro: bancoAqTras,
        bancoVentilado: bancoVent,
        tetoSolar,
        tetoPanoramico: tetoPano,
        parabrisaDesembacador: desembPara,
        retrovisorEletrico: retrovElet,
        retrovisorRebatimentoEletrico: retrovRebat,
        volanteAjusteAlturaProf: volanteAjuste,
        revestimentoBancos: revestimento,
      },
      capacidadePassageiros: {
        portas,
        passageiros,
        configuracaoFileiras: fileiras,
      },
    },
    midia: {
      fotoPrincipal: null,
      fotos: {
        "frontal-3-4": null,
        "lateral-direita": null,
        "traseira-3-4": null,
        "lateral-esquerda": null,
        "painel-cockpit": null,
        "banco-traseiro": null,
        "porta-malas-aberto": null,
        "motor-tampa-aberta": null,
        "detalhe-rodas": null,
      },
    },
  };
}

const C = {
  Flex: "TipoCombustivel.Flex",
  Gasolina: "TipoCombustivel.Gasolina",
  Hibrido: "TipoCombustivel.Hibrido",
};
const T = {
  M5: "TipoTransmissao.Manual5",
  M6: "TipoTransmissao.Manual6",
  A4: "TipoTransmissao.Automatico4",
  A5: "TipoTransmissao.Automatico5",
  A6: "TipoTransmissao.Automatico6",
  A7: "TipoTransmissao.Automatico7",
  CVT: "TipoTransmissao.CVT",
  DCT7: "TipoTransmissao.DCT7",
};
const TR = {
  D: "TipoTracao.Dianteira",
  AWD: "TipoTracao.AWD",
};
const F = {
  DV: "TipoFreio.DiscoVentilado",
  DS: "TipoFreio.DiscoSolido",
  T: "TipoFreio.Tambor",
};
const AC = {
  M: "TipoArCondicionado.Manual",
  D: "TipoArCondicionado.Digital",
  DZ: "TipoArCondicionado.DualZone",
};

console.log("Helper functions defined");
